name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # You can use other OS runners if needed

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java environment
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # You can change this based on your project requirements

    # Step 3: Cache Gradle dependencies (updated to actions/cache@v3)
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Step 4: Build with Gradle
    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    # Step 5: Run tests with Gradle (Optional but recommended)
    - name: Run tests with Gradle
      run: ./gradlew test --no-daemon

    # Step 6: Publish Gradle artifacts
    - name: Publish Gradle artifacts
      run: ./gradlew publish --no-daemon
      env:
        GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
        GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        GRADLE_DISTRIBUTION: 'path/to/your/distribution'  # Ensure this points to your distribution path if required
